### ISSUE TITLE
No longer works in the latest release

### ISSUE THREAD

**Issue by Fijxu** [t1f7/scpsl-ac-bypass#1]
they updated the anti cheat, making it worse and worse. 
![1611176529539 (Custom)](https://user-images.githubusercontent.com/61166695/108041045-cfa4a080-701c-11eb-93ff-44914ea9fdb2.png)

**Comment by Fijxu** [comment]
Works in the public beta but you can't get into servers because it is outdated, obviusly.

**Comment by t1f7** [comment]
> they updated the anti cheat, making it worse and worse.

actually you could rename Cheat Engine or other debugging tool, AC is not that smart to call something else than "FindWindowA" (or(and) FindWindowExW)

Injections are still possible if you avoid calling hooked by AC functions and won't call `CreateRemoteThread`

**Comment by Fijxu** [comment]
It's not even possible to disable the anti-cheat anyway, the game just closes. It must be a problem because I don't compile it with visual studio but I compile it with g++ from MinGW-w64?
https://z.zz.ht/pMSIf.mp4

**Comment by t1f7** [comment]
> It's not even possible to disable the anti-cheat anyway, the game just closes. It must be a problem because I don't compile it with visual studio but I compile it with g++ from MinGW-w64?
> https://z.zz.ht/pMSIf.mp4

Debug it or bypass AC other way. It throws an exception if you close the thread somewhere inside sl-ac.dll
